name: t_app_pro
description: Original tax service style Flutter app.
publish_to: "none"
version: 3.0.0+3

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0

flutter:
  uses-material-design: true
