name: t_app_pro
description: Original tax service style Flutter app.
publish_to: "none"
version: 4.0.0+4

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
