name: t_app_pro
description: Exact income tax detail page.
publish_to: "none"
version: 7.0.0+7

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
